spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${RDS_USERNAME}
    url: ${RDS_URL}
    password: ${RDS_PASSWORD}

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GOOGLE_USERNAME_FOR_SMTP}
    password: ${GOOGLE_PASSWORD_FOR_SMTP}
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  redis:
    host: localhost
    port: 6379

cloud:
  aws:
    credentials:
      access-key: ${AWS_S3_ACCESSKEY}
      secret-key: ${AWS_S3_SECRETKEY}
    region:
      static: ${AWS_S3_REGION}
    s3:
      bucket: ${AWS_S3_BUCKET}
    stack:
      auto: false

jwt:
  secretKey: ${JWT_SECRET_KEY}
  access-token-validate-in-seconds: 1800
  refresh-token-validate-in-seconds: 1209600

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  api-docs:
    groups:
      enabled: true
  swagger-ui:
    operations-sorter: alpha # alpha(알파벳 오름차순), method(HTTP메소드순)
    tags-sorter: alpha # 태그 정렬 기준
    path: /swagger-ui.html # html 문서 접속 경로
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true
    doc-expansion: none # tag, operation 펼치는 방식
  paths-to-match:

my:
  url: ${SERVER_URL}